import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import {
  Container,
  Grid,
  Navbar,
  Table,
  Text
} from '@nextui-org/react'

export default function Dashboard() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar>
          <Navbar.Brand>
            <Text b color="inherit" hideIn="xs">
              RuckNFT
            </Text>
          </Navbar.Brand>
          <Navbar.Content
            enableCursorHighlight
            activeColor="secondary"
            hideIn="xs"
            variant="underline"
          >
            <Navbar.Link isActive href="#">
              Dashboard
            </Navbar.Link>
          </Navbar.Content>
          <Navbar.Content>
            <Navbar.Link color="inherit" href="#">
              Login
            </Navbar.Link>
          </Navbar.Content>
        </Navbar>

        <Container>
          <Grid.Container gap={2}>
            <Grid xs={12}>
              <Text
                h1
                css={{
                  textGradient: "45deg, $blue600 -20%, $pink600 50%",
                }}
                weight="extrabold"
              >
                Dashboard
              </Text>
            </Grid>
            <Grid xs={12}>
              <Table
                aria-label="Example table with static content"
                css={{
                  height: "auto",
                  minWidth: "100%",
                }}
              >
                <Table.Header>
                  <Table.Column>TokenId</Table.Column>
                  <Table.Column>ROLE</Table.Column>
                  <Table.Column>STATUS</Table.Column>
                </Table.Header>
                <Table.Body>
                <Table.Row key="1">
                  <Table.Cell>Tony Reichert</Table.Cell>
                  <Table.Cell>CEO</Table.Cell>
                  <Table.Cell>Active</Table.Cell>
                </Table.Row>
                </Table.Body>
              </Table>
            </Grid>
          </Grid.Container>
        </Container>
      </main>
    </div>
  )
}
